// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utrzxwvkjuccpjrmgoeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0cnp4d3ZranVjY3Bqcm1nb2VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4MTE2OTAsImV4cCI6MjA1NTM4NzY5MH0.iJmpZShBx89tejLpNxIyT_MmBltEHJe1FhmttujXWT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);